---
# HassMediaSearchAndPlay - default
# example: play Pink Floyd
# slots: {search_query}

language: "th"
data:
  - sentences:
      - "เล่น[(เพลง|วิดีโอ)]{search_query}"
      - "เปิด(เพลง|วิดีโอ){search_query}"
    response: "default"
