---
# HassLawnMowerDock - default
# example: stop mowing

language: "en"
data:
  - sentences:
      - "(stop|cancel) mowing [[<the> ]lawn]"
      - "stop [<the>] mower"
      - "dock [<the>] [lawn] mower"
      - "return [<the>] [lawn] mower [to [the] (base|dock)]"
      - "return to [the] (base|dock)"
    example: "stop mowing"
    response: "default"
