---
# HassTimerStatus - default
# example: timer status

language: "en"
data:
  - sentences:
      - "timer[s] status"
      - "[how much] time [is] left on [the|my] timer[s]"
      - "how long [is] left on [the|my] timer[s]"
      - "status of [the|my] timer[s]"
    example: "timer status"
    response: "default"
