---
# HassMediaNext - default
# example: next track
# context_area: true

language: "en"
data:
  - sentences:
      - "next [track|item]"
      - "(skip [(to [the] next [(song|track)]|([the] (song|track)|this [(song|track)]))])"
    example: "next track"
    response: "default"
