---
# HassLawnMowerStartMowing - default
# example: start mowing

language: "en"
data:
  - sentences:
      - "(start mowing|mow) [[<the> ]lawn]"
      - "start [<the>] mower"
    example: "start mowing"
    response: "default"
