---
# HassMediaSearchAndPlay - default
# example: play The Office
# slots: {search_query}
# context_area: true

language: "en"
data:
  - sentences:
      - "play {search_query}"
    example: "play The Office"
    response: "default"
