---
# HassClimateGetTemperature - default
# example: what is the temperature
# context_area: true

language: "en"
data:
  - sentences:
      - "(<what_is>|<how_is>) [the] [current] <temp> [<here>]"
      - "how (hot|cold|warm|cool) is it [<here>]"
    example: "what is the temperature"
    response: "default"
