---
# HassFanSetSpeed - default
# example: set fans to 50%
# slots: {percentage}
# context_area: true

language: "en"
data:
  - sentences:
      - "[<set>] fan[s] [speed] [<here>] [to] {fan_speed:percentage}[%| percent]"
      - "[<set>] [the] speed [of [the]] fan[s] [<here>] [to] {fan_speed:percentage}[%| percent]"
    example: "set fans to 50%"
    response: "default"
