---
# HassGetCurrentTime - default
# example: what time is it

language: "en"
data:
  - sentences:
      - "<what_is> the [current] time"
      - "what time is it [[right] now]"
    example: "what time is it"
    response: "default"
