---
# HassGetWeather - default
# example: what is the weather like

language: "en"
data:
  - sentences:
      - "<what_is> [the] weather [like]"
    example: "what is the weather like"
    response: "default"
