---
# HassMediaPlayerMute - default
# example: mute
# context_area: true

language: "en"
data:
  - sentences:
      - "mute"
      - "mute ([the] (music|media [player[s]])) [<here>]"
    example: "mute"
    response: "default"
