---
# HassMediaPlayerUnmute - default
# example: unmute
# context_area: true

language: "en"
data:
  - sentences:
      - "unmute"
      - "unmute ([the] (music|media [player[s]])) [<here>]"
    example: "unmute"
    response: "default"
