---
# HassGetCurrentDate - default
# example: what is the date

language: "en"
data:
  - sentences:
      - "<what_is> (todays|today's|the current) date"
      - "<what_is> the date [today]"
    example: "what is the date"
    response: "default"
