---
# HassMediaPrevious - default
# example: previous track
# context_area: true

language: "en"
data:
  - sentences:
      - "previous (track|item)"
      - "go back [to the (previous|last) (song|track)]"
      - "replay [the (previous|last) (song|track)] [again]"
      - "play [the] (previous|last) [(song|track)] [again]"
    example: "previous track"
    response: "default"
