---
# HassNevermind - default
# English example: nevermind

language: "th"
data:
  - sentences:
      - "ไม่(ต้อง|เอา|เป็นไร)[(ละ|แล้ว|แล้วล่ะ)]"
      - "โอเค(ละ|แล้ว|แล้วล่ะ)"
    response: "default"
