---
# HassTimerStatus - default
# example: how much time is left on my timer

language: "th"

data:
  - sentences:
      - "[ตัว]จับเวลา(ถึงไหนแล้ว|เป็นไง|เป็นไงบ้าง|เป็นไงแล้ว|เป็นไงแล้วบ้าง|ได้เท่าไรแล้ว)"
    response: "default"
